week-1 dataset: Problem statement, dataset summary, and ini al 
observa ons.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/insurance_fraud_data.csv")
df

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.592730,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.352820,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.425230,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.342240,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.376750,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

In [3]:
df.tail(15)

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
11987,620980992,55,F,0,93,64134.4,1,1,Own,85072,...,Large,24730.289410,red,29975.28822,9583.659645,500,1518.54,11.145717,5,N
11988,621084672,40,F,0,91,59012.8,1,1,Own,20160,...,Large,31931.316140,white,19133.52963,4153.655544,2000,1239.06,9.214349,2,N
11989,621146880,48,M,1,94,61918.4,1,0,Own,20160,...,Large,31445.020900,black,21738.15301,7823.746799,1000,1622.67,11.744162,4,N
11990,621167616,59,M,0,63,65252.8,1,0,Own,80006,...,Compact,30786.609900,silver,36795.16683,3630.92594,500,1082.36,8.697555,3,Y
11991,621478656,46,M,1,97,31257.6,1,1,Own,15021,...,Large,32401.768390,silver,13635.22652,3885.037314,1000,1726.91,8.431915,3,Y
11992,621561600,69,M,1,83,67748.8,1,1,Rent,50033,...,Compact,13391.566810,gray,15435.69554,3688.149479,500,1078.65,9.800262,3,N
11993,621603072,45,F,0,77,60884.8,0,1,Rent,50013,...,Medium,6625.618162,black,22682.93206,7833.945982,1000,1324.78,8.840455,6,N
11994,621644544,41,M,1,63,59409.6,1,0,Rent,15022,...,Medium,20732.814060,gray,48782.35679,2350.450424,500,1518.54,9.941920,1,N
11995,621665280,42,M,0,71,39832.0,0,1,Own,20113,...,Large,50804.103420,gray,12208.58622,2142.045782,2000,1239.06,9.748278,6,Y
11996,621706752,31,F,1,70,88593.6,0,1,Own,80004,...,Compact,43472.514050,white,19151.51750,3152.915424,2000,1246.68,10.644784,4,N
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

In [4]:
print(df.info())
print(df.describe())

print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12002 entries, 0 to 12001
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   claim_number        12002 non-null  int64
 1   age_of_driver       12002 non-null  int64
 2   gender              12002 non-null  object
 3   marital_status      12002 non-null  object
 4   safety_rating       12002 non-null  int64
 5   annual_income       12002 non-null  float64
 6   high_education      12002 non-null  int64
 7   address_change      12002 non-null  int64
 8   property_status     12002 non-null  object
 9   zip_code            12002 non-null  int64
 10  claim_date          12002 non-null  object
 11  claim_day_of_week   12002 non-null  object
 12  accident_site       12002 non-null  object
 13  past_num_of_claims  12002 non-null  int64
 14  witness_present     12002 non-null  object
 15  liab_prct           12002 non-null  int64
 16  channel             12002 non-null  object
 17  police_report       12002 non-null  int64
 18  age_of_vehicle      12002 non-null  object
 19  vehicle_category    12002 non-null  object
 20  vehicle_price       12002 non-null  float64
 21  vehicle_color       12002 non-null  object
 22  total_claim         12002 non-null  float64
 23  injury_claim        12002 non-null  object
 24  policy deductible   12002 non-null  int64
 25  annual premium      12002 non-null  float64
 26  days open           12002 non-null  float64
 27  form defects        12002 non-null  int64
 28  fraud reported      11994 non-null  object
dtypes: float64(5), int64(11), object(13)
memory usage: 2.7+ MB
None
       claim_number  age_of_driver  safety_rating  annual_income  \
count  1.200200e+04   12002.000000   12002.000000   12002.000000
mean   3.119801e+08      43.525162      73.702966   63658.226534
std    1.795997e+08      12.201298      15.378967   17289.704559
min    1.866240e+05      19.000000       2.000000      -1.600000
25%    1.561887e+08      35.000000      66.000000   56899.200000
50%    3.121908e+08      43.000000      76.000000   60899.200000
75%    4.677938e+08      51.000000      85.000000   64697.600000
max    6.220385e+08     278.000000     100.000000  257313.600000

       high_education  address_change      zip_code  past_num_of_claims  \
count    12002.000000    12002.000000  12002.000000        12002.000000
mean         0.698134        0.576737  49762.387269            0.494918
std          0.459087        0.494097  29133.180765            0.956002
min          0.000000        0.000000      0.000000            0.000000
25%          0.000000        0.000000  20111.000000            0.000000
50%          1.000000        1.000000  50027.000000            0.000000
75%          1.000000        1.000000  80036.750000            1.000000
max          1.000000        1.000000  85083.000000            6.000000

          liab_prct  police_report  vehicle_price    total_claim  \
count  12002.000000   12002.000000   12002.000000   12002.000000
mean      49.770122       0.601066   22925.335594   22861.534958
std       33.581191       0.489699   12108.888412   12197.334761
min        0.000000       0.000000    2261.507903    2583.428985
25%       18.000000       0.000000   14087.559950   13832.784382
50%       50.000000       1.000000   20642.029325   20508.293695
75%       82.000000       1.000000   29293.641235   29205.553660
max      100.000000       1.000000  106991.684500  101818.964200

       policy deductible  annual premium     days open  form defects
count       12002.000000    12002.000000  12002.000000  12002.000000
mean         1011.039827     1268.140663      8.799198      3.969588
std           562.099581      231.670671      2.413533      1.986915
min           500.000000      433.330000      2.303305      0.000000
25%           500.000000     1082.360000      8.025550      3.000000
50%          1000.000000     1239.060000      9.268787      4.000000
75%          1000.000000     1383.490000     10.307928      5.000000
max          2000.000000     2047.590000     15.177169     13.000000
claim_number          0
age_of_driver         0
gender                0
marital_status        0
safety_rating         0
annual_income         0
high_education        0
address_change        0
property_status       0
zip_code              0
claim_date            0
claim_day_of_week     0
accident_site         0
past_num_of_claims    0
witness_present       0
liab_prct             0
channel               0
police_report         0
age_of_vehicle        0
vehicle_category      0
vehicle_price         0
vehicle_color         0
total_claim           0
injury_claim          0
policy deductible     0
annual premium        0
days open             0
form defects          0
fraud reported        8
dtype: int64

In [5]:
df.dtypes

claim_number            int64
age_of_driver           int64
gender                 object
marital_status         object
safety_rating           int64
annual_income         float64
high_education          int64
address_change          int64
property_status        object
zip_code                int64
claim_date             object
claim_day_of_week      object
accident_site          object
past_num_of_claims      int64
witness_present        object
liab_prct               int64
channel                object
police_report           int64
age_of_vehicle         object
vehicle_category       object
vehicle_price         float64
vehicle_color          object
total_claim           float64
injury_claim           object
policy deductible       int64
annual premium        float64
days open             float64
form defects            int64
fraud reported         object
dtype: object